### PR TITLE
attempting GoogleTest framework pappde/bmai#33

### PR DESCRIPTION
**Pull request by danlangford**
pappde/bmai#33

@pappde will you look at this branch and see if you can execute the tests? I want to know if you can build and execute the target `bmai_tests`. I also want to know if your IDE recognizes the tests and can help you run or debug them individually. Does everything compile well?

### CODE REVIEW

**Comment by danlangford** [comment]
It’s not as fully integrated with cmake/ctest as I would like yet

**Comment by danlangford** [comment]
**Ready for Review** @pappde 

major things to consider:
1. the core of bmai is no longer an executable but a library. this allows the lest framework to link to the library. this also requires a small wrapper `main.cpp` to make the library executable. look for function `bmai_main()` that used to be the primary `main()`
2. nested CMake. the CMake is `./test/` will auto download and arrange Google Test framework
3. a few functions moved from `bmai.cpp` because they looked to only exist to help test functionality. the functions became unit tests.

**Comment by danlangford** [comment]
I downloaded vs2017 and I can’t get the tests to show up in the Test Explorer which is a shame

**Comment by pappde** [comment]
Normally I work with a VS SLN file, which is no longer present in favor of the CMake.  Here is what happened:
1. I ran VS2022 and selected "Open Local Folder", 
2. it automatically did "CMake generation"
3. I selected "Build | Build All". 
4. It displayed some warnings about "sscanf" unsafe (which I believe we may have tracked already)
5. it successfully linked bmai.exe
6. it successfully linked bmai_tests.exe
7. I selected "Test | Run CTests for bmai". It ran 6 tests
8. it skipped "LegacyMembers.SetupTestGame"
9. all other tests passed

**Review by pappde — APPROVED** [review]

**Comment by pappde** [comment]
Test Explorer: as you observed with VS2017, the tests do NOT appear in the Test Explorer in VS2022 either.  It's strange, since it clearly can see the "CTests". I found a bug report on visualstudio.com ([https://developercommunity.visualstudio.com/t/test-explorer-does-not-show-new-google-test-cases/1374043](url)), but that's marked fixed as of last year.

If I do "Run CTests for bmai", it works, and outputs to "CMake"

If I do "Run all Tests", the "Tests" output says "No tests found to run".  Also there was an earlier error message which may be related: "No test is available in ...\out\build\x64-Debug\test\bmai_tests.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again."

**Pull request merged**
