### PR TITLE
convert README to markdown

### PR DESCRIPTION
**Pull request by danlangford**
I made the README a little more rich for displaying on GitHub. markdown is nice in that its generally still very consumable without a markdown parser/displayer 

however I did notice that technically the legacy license included with your original readme is technically non-compliant with MIT or any open source software. we might want to address that.

### CODE REVIEW

**Comment by pappde** [comment]
>  however I did notice that technically the legacy license included with your original readme is technically non-compliant with MIT or any open source software. we might want to address that.

Yes, we can address that. Is there something specific or is it more of a boilerplate issue?

**Comment by danlangford** [comment]
here is the license section of the current readme

```text
6. LICENSE AGREEMENT

By using or modifying the contained source code, you agree to the following
terms:

a) You are hereby granted license to use and modify the contained source code.

b) You are not permitted to sell or otherwise use the source code (or modified
source code) for commercial means, without consent of the original author.

c) You are not permitted to distribute the source code (or modified source code),
without consent of the original author.

d) The original author must be acknowledged in derivative works.

e) You will not use the source code (or modified source code) to assist
   you in playing online against other human players, without notifying
   your opponent that you have this advantage.

f) You will not use the source code (or modified source code) to have an
   AI player play other players (whether online through a BM web site or
   through other means), without posting a notice or otherwise
   indicating that the player is an AI.
```

the pieces of this that are not compliant with any existing open source license are as follows

> b) You are not permitted to sell or otherwise use the source code (or modified source code) for commercial means, without consent of the original author.

> c) You are not permitted to distribute the source code (or modified source code), without consent of the original author.

the "consent from original author" bit is a barrier that makes the code technically not "free" as in free to access or free to use without some additional effort (be it money, contact, agreements, etc.)

I also dont know if there is an existing open source license that covers points E and F. I have been researching and havent found anything so far.

**Comment by danlangford** [comment]
one approach could be to label that section as "Gentleman's Agreement" or "Informal Agreement" and have the code technically under MIT.

MIT legally requires that the Copyright line, with your name, follows the source code

**Comment by pappde** [comment]
revisiting this issue, I think the readme statement can be made consistent with the MIT license. Is there some boilerplate that would then replace this section, or would it simply be deleted since it's covered by the license.md?

**Comment by danlangford** [comment]
i think you can delete this section, use it to summarize and link to the
LICENSE file, or duplicate the entire license into this section.

**Comment by pappde** [comment]
added pr #61

**Pull request merged**
